// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR82J-h0-demsY9aG_xcWBBxtd_stMRSA',
    appId: '1:5775524050:web:dba52bd465392172d6ed0b',
    messagingSenderId: '5775524050',
    projectId: 'link-note-fbf10',
    authDomain: 'link-note-fbf10.firebaseapp.com',
    storageBucket: 'link-note-fbf10.firebasestorage.app',
    measurementId: 'G-MNCQ17EDTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEIZ2GwxRQomiDQnhoVLsNtnG3ibFpk3s',
    appId: '1:5775524050:android:a87f2fd763dcf856d6ed0b',
    messagingSenderId: '5775524050',
    projectId: 'link-note-fbf10',
    storageBucket: 'link-note-fbf10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg5aVwmTyITjRCb10U9BWtX385c1ZNpn4',
    appId: '1:5775524050:ios:e128ee3b948f9a34d6ed0b',
    messagingSenderId: '5775524050',
    projectId: 'link-note-fbf10',
    storageBucket: 'link-note-fbf10.firebasestorage.app',
    iosBundleId: 'com.example.linkNote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg5aVwmTyITjRCb10U9BWtX385c1ZNpn4',
    appId: '1:5775524050:ios:e128ee3b948f9a34d6ed0b',
    messagingSenderId: '5775524050',
    projectId: 'link-note-fbf10',
    storageBucket: 'link-note-fbf10.firebasestorage.app',
    iosBundleId: 'com.example.linkNote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAR82J-h0-demsY9aG_xcWBBxtd_stMRSA',
    appId: '1:5775524050:web:df4e9869b18e5c3ed6ed0b',
    messagingSenderId: '5775524050',
    projectId: 'link-note-fbf10',
    authDomain: 'link-note-fbf10.firebaseapp.com',
    storageBucket: 'link-note-fbf10.firebasestorage.app',
    measurementId: 'G-E7SS8VDP1C',
  );
}
